version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: golang-prometheus-example
    container_name: golang-prometheus-example
    restart: on-failure
    ports:
      - '8080:8080'

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/console'
    ports:
      - '9090:9090'
    depends_on:
      - app

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000'
    depends_on:
      - prometheus

volumes:
  prometheus_data: