global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: app
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets:
          - app:8080
  - job_name: pushgateway
    scrape_interval: 5s
    static_configs:
      - targets:
          - pushgateway:9091